# ????
spring.application.name=backend

# SQLite ?????
# ????????? backend/data/ielts.db
spring.datasource.url=jdbc:sqlite:data/ielts.db

# SQLite JDBC ??
spring.datasource.driver-class-name=org.sqlite.JDBC

# Flyway ???????
spring.flyway.enabled=true

# Flyway SQL ??????
spring.flyway.locations=classpath:db/migration

# MyBatis ??
# ?????? snake_case ??????? Java ? camelCase ???
#
# ???
# created_at  -> createdAt
# meta_value  -> metaValue
mybatis.configuration.map-underscore-to-camel-case=true

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
