### 查询所有 Reading Test
GET http://localhost:8080/api/reading/tests


### 创建一个 Reading Test
POST http://localhost:8080/api/reading/tests
Content-Type: application/json

{
  "title": "Cambridge IELTS 18 Test 1",
  "source": "Cambridge IELTS 18"
}


### 查询 id = 1 的 Reading Test
GET http://localhost:8080/api/reading/tests/1

### 创建 ReadingPassage
POST http://localhost:8080/api/reading/passages
Content-Type: application/json

{
  "readingTest": {
    "id": 1
  },
  "passageNumber": 1,
  "title": "The History of IELTS",
  "content": "IELTS is an international English language testing system."
}

### 查询所有 ReadingPassage
GET http://localhost:8080/api/reading/passages

### 查询 id = 1 的 ReadingPassage
GET http://localhost:8080/api/reading/passages/1

### 查询所有 ReadingQuestion
GET http://localhost:8080/api/reading/questions


### 创建 ReadingQuestion
POST http://localhost:8080/api/reading/questions
Content-Type: application/json

{
  "readingPassage": {
    "id": 1
  },
  "questionNumber": 1,
  "questionType": "TRUE_FALSE_NOT_GIVEN",
  "questionText": "IELTS is only used for university admission.",
  "correctAnswer": "FALSE",
  "explanation": "IELTS is also used for immigration, employment and other purposes."
}

### 查询所有 ReadingQuestion
GET http://localhost:8080/api/reading/questions

### 查询 id = 1 的 ReadingQuestion
GET http://localhost:8080/api/reading/questions/1

### 查询 Passage 3 下的所有 Question
GET http://localhost:8080/api/reading/passages/3/questions
